### ISSUE TITLE
[Talk] 诚邀您加入 PCL Community

### ISSUE THREAD

**Issue by WForst-Breeze** [shimoranla/shimoranla#1]
薄奚梦灵（shimoranla）：

您好！抱歉打扰。

我是 PCL Community 组织人之一，WForst Breeze，注意到您在 PCL 社区的活跃贡献，诚邀您加入 [PCL Community](https://github.com/PCL-Community)，一个非官方的 PCL 社区用户开发者组织，也是一个 PCL 社区用户开发者们的一个交流平台。您可以考虑后给予我们答复，我们会尊重您的意见~ 🧐 如果您暂时不想加入，亦或是想再观望一下，也可以选择加入我们的交流群（379026872）。十分感谢！🥳

<div align="right">
WForst Breeze
</div>

**Comment by shimoranla** [comment]
>诚邀您加入 [PCL Community](https://github.com/PCL-Community)

Accpet

**Comment by WForst-Breeze** [comment]
感谢~ 不知道方不方便加一下群呢，这样可能交流会方便一点点🤔

**Comment by shimoranla** [comment]
> 感谢~ 不知道方不方便加一下群呢，这样可能交流会方便一点点🤔

周末再说（
